export { Certificates } from "./certificates/certificates"
export { Background } from "./background/background"
export { Profile } from "./profile/profile"
export { Contact } from "./contact/contact"
export { Skills } from "./skills/skills"
export { Theme } from "./theme/theme"
export { Nav } from "./nav/nav"